---
efiBootloaderId: "ubuntu"
installEFIFallback: true
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
grubTimeout: "5"
grubInstallArguments: ["--target=x86_64-efi", "--efi-directory=/boot/efi"]
kernelLine: "quiet splash"
