---
efi:
  recommendedSize: 300MiB
  minimumSize: 100MiB

defaultFileSystemType: "ext4"

userSwapChoices:
  - none
  - small
  - suspend
  - file

ensureSuspendToDisk: true
neverCreateSwap: false

initialPartitioningChoice: erase
initialSwapChoice: small

allowManualPartitioning: true
